### ISSUE TITLE
ai-batch

### ISSUE THREAD

**Issue by LinusU** [parro-it/ai-fun#6]
How about a function to batch together several items from an async iterator? I had one use case which is where the input is an async iterator over rows from a database, and I'm calling an external api to send an email for each row. This api supports batch calls so I would prefer to send x number of rows at a time to the api. There are probably a lot of other use cases as well though :)

```typescript
batch<T>(batchSize: number, input: AsyncIterator<T>): AsyncIterator<T[]>
```

**Comment by parro-it** [comment]
Nice Idea, I think it should be really useful !
Would you mind writing the module yourself and then add here to the list?

**Comment by LinusU** [comment]
Would love to 👍
